	
service: ghopher-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10
  environment:
    FORK_URL: ${file(./config.json):FORK_URL}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
    
plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
